#!/usr/bin/env python

import os
import logging

from cli.main import cli
from lib.basics import ExecutionTime

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))

logging.basicConfig(level=logging.INFO,
                    format='%(asctime)s - %(name)-8s - %(levelname)s - %(message)s',
                    filename=os.path.join(ROOT_DIR, 'jarvis.logs'),
                    filemode='a')


@ExecutionTime(name='Jarvis')
def run_jarvis(args):
    args.func(args)


if __name__ == '__main__':
    run_jarvis(cli())
